signinSuccess:
  http_metas:
    content-type: text/html

  metas:
    title:        A Kodazi Product
    description:  A Kodazi Product
    keywords:     A Kodazi Product
    language:     en
    robots:       index, follow

  stylesheets:    [login_reg.css]

  javascripts:    [http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js]

  has_layout:     on
  layout:         layout
