<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePaymentTransaction extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('payment_transaction');
    $this->hasColumn('payment_transaction_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('gateway_transaction_id', 'string', 124, array('type' => 'string', 'notnull' => true, 'length' => '124'));
    $this->hasColumn('account_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('payment_card_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('total_value', 'decimal', 6, array('type' => 'decimal', 'default' => '0.00', 'scale' => false, 'length' => '6'));
    $this->hasColumn('currency', 'string', 8, array('type' => 'string', 'default' => 'USD', 'notnull' => true, 'length' => '8'));
    $this->hasColumn('status', 'integer', 2, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '2'));
  }

  public function setUp()
  {
    $this->hasOne('User', array('local' => 'user_id',
                                'foreign' => 'id'));

    $this->hasOne('PaymentCard', array('local' => 'payment_card_id',
                                       'foreign' => 'payment_card_id'));

    $this->hasOne('Account', array('local' => 'account_id',
                                   'foreign' => 'id'));
  }
}