<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSfGuardUser extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('sf_guard_user');
    $this->hasColumn('id', 'integer', 11, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '11'));
    $this->hasColumn('username', 'string', 128, array('type' => 'string', 'notnull' => true, 'length' => '128'));
    $this->hasColumn('algorithm', 'string', 128, array('type' => 'string', 'default' => 'sha1', 'notnull' => true, 'length' => '128'));
    $this->hasColumn('salt', 'string', 128, array('type' => 'string', 'notnull' => true, 'length' => '128'));
    $this->hasColumn('password', 'string', 128, array('type' => 'string', 'notnull' => true, 'length' => '128'));
    $this->hasColumn('is_active', 'integer', 11, array('type' => 'integer', 'default' => '1', 'notnull' => true, 'length' => '11'));
    $this->hasColumn('is_super_admin', 'integer', 11, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '11'));
    $this->hasColumn('created_at', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
    $this->hasColumn('last_login', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
    $this->hasColumn('updated_at', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
  }

}