<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUserEmail extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('user_email');
    $this->hasColumn('email_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('sequence', 'integer', 4, array('type' => 'integer', 'default' => '1', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasOne('Email', array('local' => 'email_id',
                                 'foreign' => 'email_id'));

    $this->hasOne('User', array('local' => 'user_id',
                                'foreign' => 'id'));
  }
}