<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseIssue extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('issue');
    $this->hasColumn('account_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('project_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('reported_by', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('status', 'integer', 2, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '2'));
    $this->hasColumn('level2_status', 'integer', 2, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '2'));
    $this->hasColumn('level3_status', 'integer', 2, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '2'));
    $this->hasColumn('group_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('assigned_to', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('summary', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    $this->hasColumn('description', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
    $this->hasColumn('updated', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasOne('User', array('local' => 'assigned_to',
                                'foreign' => 'id'));

    $this->hasOne('User as ReportedBy', array('local' => 'reported_by',
                                              'foreign' => 'id'));
  }
}