<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseGroup extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('groups');
    $this->hasColumn('account_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('project_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('parent_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('name', 'string', 240, array('type' => 'string', 'length' => '240'));
    $this->hasColumn('primary_owner', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('sec_owner', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('list_sequence', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('created_by', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasOne('User', array('local' => 'created_by',
                                'foreign' => 'id'));

    $this->hasOne('Account', array('local' => 'account_id',
                                   'foreign' => 'id'));

    $this->hasOne('User as PrimaryUser', array('local' => 'primary_owner',
                                               'foreign' => 'id'));

    $this->hasOne('User as SecondaryOwner', array('local' => 'sec_owner',
                                                  'foreign' => 'id'));

    $this->hasMany('Group as SubGroups', array('local' => 'id',
                                               'foreign' => 'parent_id'));

    $this->hasOne('Group', array('local' => 'parent_id',
                                 'foreign' => 'id'));
  }
}