<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePhone extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('phone');
    $this->hasColumn('phone_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('type', 'integer', 4, array('type' => 'integer', 'default' => '0', 'length' => '4'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('number', 'string', 20, array('type' => 'string', 'length' => '20'));
  }

  public function setUp()
  {
    $this->hasOne('PhoneType', array('local' => 'type',
                                     'foreign' => 'type_id'));

    $this->hasMany('UserPhone', array('local' => 'phone_id',
                                      'foreign' => 'phone_id'));
  }
}