<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseIssueTask extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('issue_task');
    $this->hasColumn('issue_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('task_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
  }

}