<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDomain extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('domain');
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('name', 'string', 148, array('type' => 'string', 'notnull' => true, 'length' => '148'));
  }

  public function setUp()
  {
    $this->hasMany('Account', array('local' => 'id',
                                    'foreign' => 'domain_id'));
  }
}