<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUserDemographics extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('user_demographics');
    $this->hasColumn('demog_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('race', 'enum', 10, array('type' => 'enum', 'values' => array(0 => 'ASIAN', 1 => 'HISPANIC', 2 => 'BLACK', 3 => 'CAUCASIAN', 4 => 'EAST_ASIAN'), 'length' => '10'));
    $this->hasColumn('income_level', 'enum', 1, array('type' => 'enum', 'values' => array(0 => '1', 1 => '2', 2 => '3', 3 => '4', 4 => '5'), 'length' => '1'));
    $this->hasColumn('age', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('sex', 'integer', 2, array('type' => 'integer', 'length' => '2'));
    $this->hasColumn('zip', 'string', 12, array('type' => 'string', 'length' => '12'));
  }

}