<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUserRole extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('user_role');
    $this->hasColumn('role_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('role_name', 'string', 240, array('type' => 'string', 'notnull' => true, 'length' => '240'));
    $this->hasColumn('role_category', 'string', 240, array('type' => 'string', 'length' => '240'));
  }

  public function setUp()
  {
    $this->hasMany('ProjectUserRole', array('local' => 'role_id',
                                            'foreign' => 'role_id'));

    $this->hasMany('TeamUser', array('local' => 'role_id',
                                     'foreign' => 'user_role_id'));
  }
}