<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseKodaziSession extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('session');
    $this->hasColumn('id', 'string', 255, array('type' => 'string', 'primary' => true, 'length' => '255'));
    $this->hasColumn('time', 'integer', 8, array('type' => 'integer', 'default' => '0', 'length' => '8'));
    $this->hasColumn('data', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
  }

}