<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNotifMessage extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('notif_message');
    $this->hasColumn('message_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('body', 'string', 2147483647, array('type' => 'string', 'notnull' => true, 'length' => '2147483647'));
    $this->hasColumn('created_by', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('notif_type', 'integer', 2, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '2'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('sub_message_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('title', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    $this->hasColumn('subject', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
  }

  public function setUp()
  {
    $this->hasOne('User', array('local' => 'created_by',
                                'foreign' => 'id'));

    $this->hasOne('NotifMessage', array('local' => 'sub_message_id',
                                        'foreign' => 'message_id'));
  }
}