<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTeam extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('team');
    $this->hasColumn('team_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('project_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('name', 'string', 120, array('type' => 'string', 'notnull' => true, 'length' => '120'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasMany('AccountUser', array('local' => 'team_id',
                                        'foreign' => 'team_id'));

    $this->hasMany('ProjectUser', array('local' => 'team_id',
                                        'foreign' => 'team_id'));

    $this->hasMany('TeamUser', array('local' => 'team_id',
                                     'foreign' => 'team_id'));
  }
}