<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePlanFeature extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('plan_feature');
    $this->hasColumn('plan_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('space', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('iphone_access', 'string', 1, array('type' => 'string', 'fixed' => 1, 'length' => '1'));
    $this->hasColumn('ssl_on', 'string', 1, array('type' => 'string', 'fixed' => 1, 'length' => '1'));
    $this->hasColumn('data_backup', 'string', 1, array('type' => 'string', 'fixed' => 1, 'length' => '1'));
    $this->hasColumn('num_users', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('num_projects', 'integer', 4, array('type' => 'integer', 'length' => '4'));
  }

  public function setUp()
  {
    $this->hasOne('Plan', array('local' => 'plan_id',
                                'foreign' => 'plan_id'));
  }
}