<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSfGuardPermission extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('sf_guard_permission');
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('name', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('description', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    $this->hasColumn('created_at', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
    $this->hasColumn('updated_at', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasMany('SfGuardGroupPermission', array('local' => 'id',
                                                   'foreign' => 'permission_id'));

    $this->hasMany('SfGuardUserPermission', array('local' => 'id',
                                                  'foreign' => 'permission_id'));
  }
}