<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEventLog extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('event_log');
    $this->hasColumn('event_log_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('account_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('action', 'enum', 7, array('type' => 'enum', 'values' => array(0 => 'CREATE', 1 => 'READ', 2 => 'UPDATE', 3 => 'DELETE', 4 => 'COMMENT', 5 => 'ASSIGN'), 'length' => '7'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('project_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('group_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('task_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('file_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('action_detail', 'string', 248, array('type' => 'string', 'length' => '248'));
  }

  public function setUp()
  {
    $this->hasOne('File', array('local' => 'file_id',
                                'foreign' => 'file_id'));

    $this->hasOne('User', array('local' => 'user_id',
                                'foreign' => 'id'));

    $this->hasOne('Account', array('local' => 'account_id',
                                   'foreign' => 'id'));
  }
}