<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUserPref extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('user_pref');
    $this->hasColumn('account_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('prefs', 'string', 2048, array('type' => 'string', 'notnull' => true, 'length' => '2048'));
  }

  public function setUp()
  {
    $this->hasOne('Account', array('local' => 'account_id',
                                   'foreign' => 'id'));

    $this->hasOne('User', array('local' => 'user_id',
                                'foreign' => 'id'));
  }
}