<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseFile extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('file');
    $this->hasColumn('file_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('is_public', 'integer', 2, array('type' => 'integer', 'default' => '0', 'length' => '2'));
    $this->hasColumn('project_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasMany('Comment', array('local' => 'file_id',
                                    'foreign' => 'file_id'));

    $this->hasMany('EventLog', array('local' => 'file_id',
                                     'foreign' => 'file_id'));

    $this->hasMany('FileInfo', array('local' => 'file_id',
                                     'foreign' => 'file_id'));

    $this->hasMany('FileIssue', array('local' => 'file_id',
                                      'foreign' => 'file_id'));

    $this->hasMany('FileTask', array('local' => 'file_id',
                                     'foreign' => 'file_id'));

    $this->hasMany('FileUser', array('local' => 'file_id',
                                     'foreign' => 'file_id'));

    $this->hasMany('FileVersion', array('local' => 'file_id',
                                        'foreign' => 'file_id'));

    $this->hasMany('ProjectFile', array('local' => 'file_id',
                                        'foreign' => 'file_id'));
  }
}