<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAuditLog extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('audit_log');
    $this->hasColumn('id', 'integer', 8, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '8'));
    $this->hasColumn('log', 'string', 2147483647, array('type' => 'string', 'notnull' => true, 'length' => '2147483647'));
    $this->hasColumn('created_time', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('action_name', 'string', 244, array('type' => 'string', 'length' => '244'));
  }

}