<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEmail extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('email');
    $this->hasColumn('email_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('email', 'string', 240, array('type' => 'string', 'notnull' => true, 'length' => '240'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasOne('User', array('local' => 'user_id',
                                'foreign' => 'id'));

    $this->hasMany('ProjectEmail', array('local' => 'email_id',
                                         'foreign' => 'email_id'));

    $this->hasMany('UserEmail', array('local' => 'email_id',
                                      'foreign' => 'email_id'));
  }
}