<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseProject extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('project');
    $this->hasColumn('account_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('created_by', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('name', 'string', 240, array('type' => 'string', 'notnull' => true, 'length' => '240'));
    $this->hasColumn('status', 'integer', 4, array('type' => 'integer', 'default' => '0', 'length' => '4'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('address_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('description', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
  }

  public function setUp()
  {
    $this->hasOne('User', array('local' => 'created_by',
                                'foreign' => 'id'));
  }
}