<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAddress extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('address');
    $this->hasColumn('address_id', 'integer', 11, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '11'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('street_1', 'string', 48, array('type' => 'string', 'length' => '48'));
    $this->hasColumn('street_2', 'string', 128, array('type' => 'string', 'length' => '128'));
    $this->hasColumn('street_3', 'string', 128, array('type' => 'string', 'length' => '128'));
    $this->hasColumn('city', 'string', 128, array('type' => 'string', 'length' => '128'));
    $this->hasColumn('state', 'string', 128, array('type' => 'string', 'length' => '128'));
    $this->hasColumn('country', 'string', 128, array('type' => 'string', 'length' => '128'));
    $this->hasColumn('zip', 'integer', 11, array('type' => 'integer', 'length' => '11'));
    $this->hasColumn('phone_id', 'integer', 11, array('type' => 'integer', 'length' => '11'));
  }

  public function setUp()
  {
    $this->hasOne('Phone', array('local' => 'phone_id',
                                 'foreign' => 'phone_id'));

    $this->hasMany('Account', array('local' => 'address_id',
                                    'foreign' => 'address_id'));

    $this->hasMany('Profile', array('local' => 'address_id',
                                    'foreign' => 'address_id'));

    $this->hasMany('Project', array('local' => 'address_id',
                                    'foreign' => 'address_id'));

    $this->hasMany('UserAddress', array('local' => 'address_id',
                                        'foreign' => 'address_id'));
  }
}