<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUserType extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('user_type');
    $this->hasColumn('type_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('type', 'string', 48, array('type' => 'string', 'notnull' => true, 'length' => '48'));
    $this->hasColumn('description', 'string', 255, array('type' => 'string', 'length' => '255'));
  }

}