<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMilestone extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('milestone');
    $this->hasColumn('milestone_id', 'integer', 11, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '11'));
    $this->hasColumn('sub_milestone_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('created_by', 'integer', 11, array('type' => 'integer', 'notnull' => true, 'length' => '11'));
    $this->hasColumn('project_id', 'integer', 11, array('type' => 'integer', 'notnull' => true, 'length' => '11'));
    $this->hasColumn('name', 'string', 240, array('type' => 'string', 'notnull' => true, 'length' => '240'));
    $this->hasColumn('status', 'integer', 11, array('type' => 'integer', 'default' => '0', 'length' => '11'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('primary_owner', 'integer', 11, array('type' => 'integer', 'length' => '11'));
    $this->hasColumn('sec_owner', 'integer', 11, array('type' => 'integer', 'length' => '11'));
    $this->hasColumn('description', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    $this->hasColumn('start_time', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
    $this->hasColumn('end_time', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasOne('Milestone', array('local' => 'sub_milestone_id',
                                     'foreign' => 'milestone_id'));

    $this->hasOne('User', array('local' => 'primary_owner',
                                'foreign' => 'id'));

    $this->hasOne('User as User_2', array('local' => 'sec_owner',
                                          'foreign' => 'id'));

    $this->hasOne('Project', array('local' => 'project_id',
                                   'foreign' => 'project_id'));

    $this->hasOne('User as User_4', array('local' => 'created_by',
                                          'foreign' => 'id'));

    $this->hasMany('Comment', array('local' => 'milestone_id',
                                    'foreign' => 'milestone_id'));

    $this->hasMany('EventLog', array('local' => 'milestone_id',
                                     'foreign' => 'milestone_id'));

    $this->hasMany('Task', array('local' => 'milestone_id',
                                 'foreign' => 'milestone_id'));
  }
}