<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMessage extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('message');
    $this->hasColumn('messg_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('subject', 'string', 2048, array('type' => 'string', 'default' => 'Untitled Message', 'length' => '2048'));
    $this->hasColumn('submitted_by', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('status', 'string', 1, array('type' => 'string', 'fixed' => 1, 'default' => '1', 'notnull' => true, 'length' => '1'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('messg_sub_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('account_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('project_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('body', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
  }

  public function setUp()
  {
    $this->hasOne('Message', array('local' => 'messg_sub_id',
                                   'foreign' => 'messg_id'));

    $this->hasOne('Account', array('local' => 'account_id',
                                   'foreign' => 'id'));

    $this->hasOne('User', array('local' => 'submitted_by',
                                'foreign' => 'id'));

    $this->hasMany('MessageSubs', array('local' => 'messg_id',
                                        'foreign' => 'messg_id'));

    $this->hasMany('MessageTag', array('local' => 'messg_id',
                                       'foreign' => 'messg_id'));
  }
}