<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBlacklistWord extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('blacklist_word');
    $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('word', 'string', 48, array('type' => 'string', 'length' => '48'));
  }

}