<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePaymentCard extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('payment_card');
    $this->hasColumn('payment_card_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('first_name', 'string', 148, array('type' => 'string', 'notnull' => true, 'length' => '148'));
    $this->hasColumn('last_name', 'string', 148, array('type' => 'string', 'notnull' => true, 'length' => '148'));
    $this->hasColumn('card_num', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('card_type', 'string', 5, array('type' => 'string', 'notnull' => true, 'length' => '5'));
    $this->hasColumn('expiry_month', 'string', 2, array('type' => 'string', 'notnull' => true, 'length' => '2'));
    $this->hasColumn('expiry_year', 'string', 4, array('type' => 'string', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('ccv', 'string', 8, array('type' => 'string', 'notnull' => true, 'length' => '8'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('status', 'integer', 2, array('type' => 'integer', 'default' => '1', 'notnull' => true, 'length' => '2'));
  }

  public function setUp()
  {
    $this->hasMany('PaymentTransaction', array('local' => 'payment_card_id',
                                               'foreign' => 'payment_card_id'));
  }
}