<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAccountGroup extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('account_group');
    $this->hasColumn('group_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('account_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('name', 'string', 240, array('type' => 'string', 'notnull' => true, 'length' => '240'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasOne('Account', array('local' => 'account_id',
                                   'foreign' => 'id'));
  }
}