<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseComment extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('comment');
    $this->hasColumn('comment_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('account_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('submitted_by', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('status', 'string', 1, array('type' => 'string', 'fixed' => 1, 'default' => '0', 'notnull' => true, 'length' => '1'));
    $this->hasColumn('comment_text', 'string', 2147483647, array('type' => 'string', 'notnull' => true, 'length' => '2147483647'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('project_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('group_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('task_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    $this->hasColumn('file_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
  }

  public function setUp()
  {
    $this->hasOne('User', array('local' => 'submitted_by',
                                'foreign' => 'id'));

    $this->hasOne('Account', array('local' => 'account_id',
                                   'foreign' => 'id'));

    $this->hasOne('File', array('local' => 'file_id',
                                'foreign' => 'file_id'));
  }
}