<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAccountFile extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('account_file');
    $this->hasColumn('account_id', 'integer', 11, array('type' => 'integer', 'primary' => true, 'length' => '11'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('alf_user_id', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('alf_user_password', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('alf_path', 'string', 448, array('type' => 'string', 'length' => '448'));
    $this->hasColumn('alf_node_id', 'string', 255, array('type' => 'string', 'length' => '255'));
  }

  public function setUp()
  {
    $this->hasOne('Account', array('local' => 'account_id',
                                   'foreign' => 'account_id'));
  }
}