<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMessageSubs extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('message_subs');
    $this->hasColumn('messg_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('subscriber_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
  }

  public function setUp()
  {
    $this->hasOne('User', array('local' => 'subscriber_id',
                                'foreign' => 'id'));

    $this->hasOne('Message', array('local' => 'messg_id',
                                   'foreign' => 'messg_id'));
  }
}