<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSfGuardUserGroup extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('sf_guard_user_group');
    $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('group_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('created_at', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
    $this->hasColumn('updated_at', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasOne('SfGuardGroup', array('local' => 'group_id',
                                        'foreign' => 'id'));

    $this->hasOne('SfGuardUser', array('local' => 'user_id',
                                       'foreign' => 'id'));
  }
}