<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseFileMessage extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('file_message');
    $this->hasColumn('file_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('messg_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
  }

  public function setUp()
  {
    $this->hasOne('File', array('local' => 'file_id',
                                'foreign' => 'file_id'));

    $this->hasOne('Message', array('local' => 'messg_id',
                                   'foreign' => 'messg_id'));
  }
}