<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseFileVersion extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('file_version');
    $this->hasColumn('version_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('file_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('version', 'integer', 4, array('type' => 'integer', 'default' => '1', 'length' => '4'));
    $this->hasColumn('created', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasOne('File', array('local' => 'file_id',
                                'foreign' => 'file_id'));

    $this->hasMany('FileInfo', array('local' => 'version_id',
                                     'foreign' => 'version_id'));
  }
}