<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePhoneType extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('phone_type');
    $this->hasColumn('type_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('name', 'string', 20, array('type' => 'string', 'length' => '20'));
  }

  public function setUp()
  {
    $this->hasMany('Phone', array('local' => 'type_id',
                                  'foreign' => 'type'));
  }
}