<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePlan extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('plan');
    $this->hasColumn('plan_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('type', 'string', 48, array('type' => 'string', 'notnull' => true, 'length' => '48'));
    $this->hasColumn('price', 'decimal', 3, array('type' => 'decimal', 'scale' => false, 'length' => '3'));
    $this->hasColumn('description', 'string', 255, array('type' => 'string', 'length' => '255'));
  }

  public function setUp()
  {
    $this->hasMany('Account', array('local' => 'plan_id',
                                    'foreign' => 'plan_id'));

    $this->hasMany('PlanFeature', array('local' => 'plan_id',
                                        'foreign' => 'plan_id'));
  }
}