<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseIssueMeta extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('issue_meta');
    $this->hasColumn('issue_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    $this->hasColumn('severity', 'string', 24, array('type' => 'string', 'length' => '24'));
    $this->hasColumn('frequency', 'string', 8, array('type' => 'string', 'length' => '8'));
    $this->hasColumn('hardware', 'string', 24, array('type' => 'string', 'length' => '24'));
    $this->hasColumn('version', 'string', 12, array('type' => 'string', 'length' => '12'));
  }

}