<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class File extends BaseFile
{
	public function getLatestVersion(){
		$q = Doctrine_Query::create()
			->select('fi.*')
			->from('FileInfo fi')
			->innerJoin('fi.FileVersion fv')
			->where('fv.file_id = ?', $this->file_id)
			->orderBy('fv.version desc');
		return $q->fetchOne();
		
	}
	
	public function getLatestVersionNum(){
		$fileVersion =  Doctrine_Query::create()
			->select('fv.*')
			->from('FileVersion fv')
			->where('fv.file_id = ?', $this->file_id)
			->orderBy('fv.version desc')
			->fetchOne();
			
		if ($fileVersion){
			return $fileVersion->getVersion();
		}else{
			return 0;
		}
		
		
	}
	

}