<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FileTable extends Doctrine_Table
{
	
	public function getProjectFiles($projectId){
		/**
		 * select * from file_version fv inner join file f on f.file_id = fv.parent_file_id
		 * where f.project_id = 7 group by fv.parent_file_id order by fv.created desc
		 */
		$q = Doctrine_Query::create()
			->select('f.*')
			->from('File f')
			//->innerJoin('fv.File f with fv.file_id = f.file_id')
			->where('f.project_id = ?', $projectId);
//			->groupBy('fv.file_id')
//			->orderBy('fv.created desc');
			
		return $q->execute();
	}
	

}