<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessageTable extends Doctrine_Table
{

	
  	public function getUnsentMessages(){
  		$q = Doctrine_Query::create()
			->from('message m')
			->where('m.status = 1')
			->orderBy('m.created asc');

		return $q->execute();
  	}
	
	
}