<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Message extends BaseMessage
{
  public function setUp()
  {
    parent::setUp();
  	$this->hasMany('Message as Messages', array('local' => 'messg_id',
                                   			'foreign' => 'messg_sub_id',
  											'cascade' => array('delete')));
  	$this->hasMany('MessageSubs', array('local' => 'messg_id',
                                        'foreign' => 'messg_id',
  										'cascade' => array('delete')));
  }

}