<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Profile extends BaseProfile
{

	public function setUp()
	{
		 
		parent::setUp();

		$this->hasOne('Email', array('local' => 'user_id',
                                'foreign' => 'user_id'));
		 
	}


}