<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectAccount extends BaseProjectAccount
{

	public function setUp()
  	{
  	
  		parent::setUp();
  		
  		$this->hasMany('Project', array('local' => 'project_id',
                                 'foreign' => 'project_id',
  								 'cascade' => array('delete')
  									)
  					 );
  	}
	
	
}