<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectUser extends BaseProjectUser
{
	
	public static function getProjectUserByPidUid($uid, $pid){
		$q = Doctrine_Query::create()
    		->from('ProjectUser pu')
    		->where('pu.user_id = ? and pu.project_id = ?', array($uid, $pid));
		$q->execute();

		return $q->fetchOne();
		
	}

}