<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Project extends BaseProject
{
	
	public function setUp()
  	{
  	
  		parent::setUp();
  		
  		$this->hasMany('Task as Tasks', array('local' => 'id',
                                 'foreign' => 'project_id',
  								 'cascade' => array('delete')
  									)
  						);
  		$this->hasMany('ProjectUser', array('local' => 'id',
                                 'foreign' => 'project_id',
  								 'cascade' => array('delete')
  									)
  						);
  		$this->hasMany('ProjectUserRole', array('local' => 'id',
                                 'foreign' => 'project_id',
  								 'cascade' => array('delete')
  									)
  						);
  		$this->hasMany('Team', array('local' => 'id',
                                 'foreign' => 'project_id',
  								 'cascade' => array('delete')
  									)
  		);
  		
  		
  	
  	}
  	
  	
	
	
  	public function getNewTaskId($accountId){
  		$q = new Doctrine_Query();
		$q->select('t.*');
		$q->from('Task t');
		$q->where('t.account_id = ?', $accountId);
		$q->andWhere('t.project_id = ?', $this->id);
		$q->orderBy('t.id desc');
		$q->limit(1);

		$task =  $q->fetchOne();
		return $task->id + 1;
  	}
  	
  	public function getGroups(){
  		
  		$q = new Doctrine_Query();
		$q->select('g.*');
		$q->from('Group g');
		$q->where('g.account_id = ?', $this->account_id);
		$q->addWhere('g.project_id = ?', $this->id);
		$q->orderBy('g.list_sequence desc');

		return $q->execute();
  	}
	

}