<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Task extends BaseTask
{
	public function setUp()
	{
		parent::setUp();
		$this->hasMany('EventLog as History', array('local' => 'task_id',
                                'foreign' => 'task_id'));
		$this->hasOne('Profile', array('local' => 'owner',
                                'foreign' => 'profile_id'));

	    $this->hasOne('Profile as Creator', array('local' => 'created_by',
                                          'foreign' => 'profile_id'));
	}
	
	public function getDueDateFormatted()
	{
		return 'ady';
	}

	public function save( Doctrine_Connection $con = null)
	{

		if (!$con){
			$con = Doctrine_Manager::connection();
		}

		try {
			$con->beginTransaction();
			$ret = parent::save($con);
				
			//create an event log
			$evl = new EventLog();
			$evl->setAccountId($this->getMilestone()->getProject()->getProjectAccount()->getAccountId());
			$evl->setTaskId($this->getTaskId());
			$evl->setUserId($this->getCreatedBy());
			$evl->setAction($id?'UPDATE':'CREATE');
			$evl->setActionDetail(serialize($this));
			$evl->setCreated(date("Y-m-d H:i:s"));
			$evl->save($con);

				
				

			$this->updateLuceneIndex();
			$con->commit();
			return $ret;

		}catch (Doctrine_Exception $e) {
			$con->rollback();
			error_log ($e->getMessage());
			return false;
		}

	}



	public function updateLuceneIndex()
	{

		$accountId = $this->getProject()->getProjectAccount()->getId();

		$index = TaskTable::getLuceneIndex($accountId);

		// remove an existing entry
		if ($hit = $index->find('pk:'.$this->getTaskId())){
			$index->delete($hit->id);
		}

		// don't index expired events
		//      if ($this->getEventDate() < today)
		//      {
		//          return;
		//      }

		$doc = new Zend_Search_Lucene_Document();

		// store primary key URL to identify it in the search results
		$doc->addField(Zend_Search_Lucene_Field::UnIndexed('pk', $this->getTaskId()));

		// index fields
		$doc->addField(Zend_Search_Lucene_Field::UnStored('name', $this->getName(), 'utf-8'));
		$doc->addField(Zend_Search_Lucene_Field::UnStored('description', $this->getDescription(), 'utf-8'));

		// add job to the index
		$index->addDocument($doc);
		$index->commit();
	}


	// lib/model/JobeetJob.php
	public function delete(Doctrine_Connection $con = null)
	{

		if (!$con){
			$con = Doctrine_Manager::connection();
		}

		try {
			
			
			$accountId = $this->getProject()->getProjectAccount()->getId();
				
			$index = TaskTable::getLuceneIndex($accountId);
			if ($hit = $index->find('pk:'.$this->getTaskId())){
				$index->delete($hit->id);
			}
				

			//create an event log
//			$evl = new EventLog();
//			$evl->setUserId($this->getCreatedBy());
//			$evl->setAction('DELETE');
//			$evl->setActionDetail(serialize(array(get_class($this), $this->getName())));
//			$evl->setCreated(date("Y-m-d H:i:s"));
//			$evl->save($con);

			return parent::delete($con);

		}catch (Doctrine_Exception $e) {
			$con->rollback();
			error_log ($e->getMessage());
			return false;
		}
	}

}