<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User extends sfGuardUser
{

	public function setUp()
	{
		parent::setUp();
		
		$this->hasOne('Email', array('local' => 'id',
                                'foreign' => 'user_id'));
	}

}