hubSuccess:
  http_metas:
    content-type: text/html

  stylesheets:    [login_reg.css]

  javascripts:    []

  has_layout:     on
  layout:         layout_account
  
  
manageSuccess:
  http_metas:
    content-type: text/html

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout_project
  
viewBillingSuccess:
  http_metas:
    content-type: text/html

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout_project